<?php

declare(strict_types=1);

namespace ByLexus\TaskRunner\Queue\Db;

use ByLexus\TaskRunner\Queue\QueueConfiguration;

final class PostgresPlatform extends AbstractDatabasePlatform {
    public function getName(): string {
        return 'postgresql';
    }

    public function supportsNotifications(): bool {
        return true;
    }

    public function supportsInsertReturning(): bool {
        return true;
    }

    public function supportsUpdateReturning(): bool {
        return true;
    }

    protected function defaultNamespaceExpression(\ByLexus\TaskRunner\Queue\QueueConfiguration $configuration): string {
        return $configuration->getSchemaName() === null ? 'current_schema()' : ':schema_name';
    }

    protected function queueTableStatement(QueueConfiguration $configuration): string {
        return sprintf(
            <<<'SQL'
CREATE TABLE IF NOT EXISTS %s (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_class TEXT NOT NULL,
    step_class TEXT NULL,
    task_status TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 3,
    task_created_at TIMESTAMPTZ NOT NULL,
    task_started_at TIMESTAMPTZ NULL,
    task_finished_at TIMESTAMPTZ NULL,
    cleanup_at TIMESTAMPTZ NULL,
    step_status TEXT NULL,
    step_attempt INTEGER NOT NULL DEFAULT 0,
    step_started_at TIMESTAMPTZ NULL,
    step_finished_at TIMESTAMPTZ NULL,
    payload_json JSONB NULL,
    result_json JSONB NULL,
    error_json JSONB NULL,
    available_at TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ NULL,
    claimed_by TEXT NULL,
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    cancel_reason TEXT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    log TEXT NULL
)
SQL,
            $this->queueTableName($configuration),
        );
    }

    protected function blobTableStatement(QueueConfiguration $configuration): string {
        return sprintf(
            <<<'SQL'
CREATE TABLE IF NOT EXISTS %s (
    blob_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    content BYTEA NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT %s FOREIGN KEY (task_id) REFERENCES %s (task_id) ON DELETE CASCADE
)
SQL,
            $this->blobTableName($configuration),
            $this->quoteIdentifier($this->derivedName($configuration, 'blob_task_id_fk')),
            $this->queueTableName($configuration),
        );
    }

    protected function priorityMigrationStatement(QueueConfiguration $configuration): ?string {
        return sprintf(
            'ALTER TABLE %s ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 3',
            $this->queueTableName($configuration),
        );
    }

    protected function logMigrationStatement(QueueConfiguration $configuration): ?string {
        return sprintf(
            'ALTER TABLE %s ADD COLUMN IF NOT EXISTS log TEXT NULL',
            $this->queueTableName($configuration),
        );
    }

    protected function fetchIndexNames(\PDO $connection, QueueConfiguration $configuration, string $tableName): array {
        $statement = $connection->prepare(sprintf(
            'SELECT indexname
                FROM pg_indexes
                WHERE schemaname = %s
                  AND tablename = :table_name',
            $this->defaultNamespaceExpression($configuration),
        ));
        $statement->execute($this->namespaceParameters($configuration, [
            'table_name' => $tableName,
        ]));

        /** @var list<string> $indexNames */
        $indexNames = $statement->fetchAll(\PDO::FETCH_COLUMN);

        return $indexNames;
    }

    protected function defaultNamespaceName(): string {
        return 'public';
    }
}
